name: wallcraft_manager
description: "A Flutter plugin for wallpaper set (home screen, lock screen, both)."
version: 1.0.0
homepage: https://github.com/mahadydev/wallcraft_manager

environment:
  sdk: 3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wallcraftai.wp.plugin.wallcraft_manager
        pluginClass: WallcraftManagerPlugin
      ios:
        pluginClass: WallcraftManagerPlugin
