name: wallcraft_manager
description: A Flutter plugin for setting wallpapers and saving images to gallery on Android and iOS. Supports different wallpaper types and modern platform APIs.
version: 1.0.0
homepage: https://github.com/mahadydev/wallcraft_manager
repository: https://github.com/mahadydev/wallcraft_manager
issue_tracker: https://github.com/mahadydev/wallcraft_manager/issues
documentation: https://github.com/mahadydev/wallcraft_manager#readme

topics:
  - wallpaper
  - gallery
  - images
  - android
  - ios

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: wp.plugin.wallcraft.manager
        pluginClass: WallcraftManagerPlugin
      ios:
        pluginClass: WallcraftManagerPlugin
